### ISSUE TITLE
could you guys make a colab notebook

### ISSUE THREAD

**Issue by GeorvityLabs** [PeterFWS/Structure-PLP-SLAM#10]
would be great if you guys can make a colab notebook for testing monocular scene videos (.mp4)
it would be great if a user can upload their .mp4 video as input and get a map output.
Hope you guys will have a look into this , would be great to test this on google colab (using the T4 GPU)

**Comment by PeterFWS** [comment]
Hi,

thanks for your suggestion. Since SLAM is meant to be run in real-time, at least, so we have not investigated any notebook such as colab (with which I have no experience to deploy a c++ framework), or configured the SLAM running on the cloud just for generating a map.

We are happy if you wanted to contribute anything related to this.

Best,

**Comment by GeorvityLabs** [comment]
@PeterFWS  , yes , I would be interested in potentially making a notebook.
i'll try to have a closer look at the project to see what can be done.

**Comment by PeterFWS** [comment]
Ok, thank you.
